

    var dataSet = [
["adib.gif","ADIB ","Cluster O, O2 Residence, ShopNo:2","04-701-8880","Banks & ATMs","","http://adib.ae/"],
["emiratesislamic.png","Emirates Islamic Bank","Al Mas Tower","06-059-9995","Banks & ATMs","","http://emiratesislamic.ae"],
["bankofbarodauae.gif","Bank of Baroda","Al Mas Tower","04-395-0944","Banks & ATMs","","http://bankofbarodauae.ae/"],
["","RAK Bank (ATM)","Cluster B","NA","Banks & ATMs","",""],
["","Dubai Bank ","","800-555","Banks & ATMs","",""],
["","NBD Bank","Al Mas Tower, Ground Floor","600 54 0000","Banks & ATMs","","http://emiratesnbd.com/en/"],
["uab.jpg","United Arab Bank","Almas Tower","800-474","Banks & ATMs","","http://uab.ae"],
["uab.jpg","United Arab Bank (ATM)","Cluster A","800-474","Banks & ATMs","","http://uab.ae"],
["","Mashreq Bank plus ATM (24 hr)","Reef Tower","04-424-4444","Banks & ATMs","","http://mashreqbank.com/"],
["noorbank.png","Noor Bank ATM","Almas Tower","800 6667","Banks & ATMs","","http://noorbank.com/"],
["","Union National Bank (ATM)","Green Lakes Tower, S1","NA","Banks & ATMs","","http://unb.com/english/index.aspx"],

["heeragoldtradingdmcc.png","Heera Gold Trading DMCC","Cluster T, Fortune Executive Tower","04-432-8727","Trading Services","","https://heeragoldtradingdmcc.com/"],
["","Diamon Resources DMCC","Cluster T, Fortune Executive Tower","04-374-6945","Trading Services","","http://diamondresourcesdmcc.com"],
["du.jpg","Du Bill Pay machine","Almas Tower","","OtherServices","","http://du.ae/"],
["sovereigngroup.png","Sovereign Corporate Services JLT","Cluster O, Reef Tower O1","04-448-6010","Corporate Services","","http://sovereigngroup.com/"],
["gkd.png","GKD World Wide Weave","Fortune Tower, Unit:1308","04-375-7070","OtherServices","","http://gkd.uk.com/"],
["","Indo Arab Insurance","cluster Q2, Dubai Gate 1","04-425-4327","Insurance","","http://sovereigngroup.com/downloads/SCS-Brochure.pdf"],
["cartaplusme.jpg","Carta Plus JLT","Fortune Tower","04-439-1795","OtherServices","","http://cartaplusme.com"],
["cheznouspr.png","Chenz nous (PR consultancy)","Fortune tower, Unit:1107","04-366-9449","Consultancy","","http://cheznouspr.com/"],
["basementprojectme.png","The Basement Project","Fortune Tower","04-420-1930","OtherServices","","http://basementprojectme.com"],
["menthanex.png","Methanex Middle East (Methanol supplier)","Fortune Tower","04-438-0299","OtherServices","","http://methanex.com"],
["","Ozon Techno Commercial sourcing & Distribution","Fortune Tower","04-448-6088","IT Services","","http://ozongulf.com"],
["settlefirst.jpg","SettleFirst (Cost Consultant Company)","Fortune Tower","04-453-9398","OtherServices","","http://settlefirst.com"],
["robtstone.jpg","Robt. Stone ME LLC (Engineering & Construction)","Fortune Tower, 901","04-428-9404","Engineering Services","","http://robtstone.com"],
["omraninc.png","Omran Holding Group (Engineering Consultancy)","Fortune Tower","04-884-0344","Engineering Services","","http://omraninc.com"],
["trasix.png","Trasix (Advertising & Designing)","Fortune Tower","04-368-9524","Advertising Services","","http://trasix.com"],
["nautic-group.png","Nautic Middle East (Engineering Consultant)","Fortune Tower","04-362-3344","Engineering Services","","http://nautic-group.com"],
["gkfx.png","GKFX Financial Services Ltd","Fortune Tower","04-368-7274","Financial Services","","http://gkfx.com"],
["st-thomasconsulting.png","St Thomas Consulting","Fortune Tower","04-368-8088","OtherServices","","http://st-thomasconsulting.com"],
["","Sika UAE (Trading Company)","Frtune Tower","04-439-8200","Trading Services","","http://gcc.sika.com"],
["infoquestit.png","Infoquest (IT Services)","One Lake Plaza","050-856-6441","IT Services","","http://infoquestit.com"],
["lazertechsolutions.png","Lazer Technology Solutions (IT services)","Fortune Tower","04-457-2260","IT Services","","http://lazertechsolutions.com"],
["mepcogulf.png","Mepco (Trading Fine Paper Supplier)","Fortune Tower","04-423-0640","OtherServices","","http://mepcogulf.com"],
["pacificbasin.gif","Pacific Basin (Shipping)","Fortune Tower","04-424-5977","Logistic Services","","http://pacificbasin.com"],
["kse.gif","KSE Electronicals (Transmission & Distribution)","Fortune Tower","04-420-6905","Engineering Services","","http://kse.in"],
["fourfrontiers.gif","Four Frontiers (Hotels & Restaurants Interiors Dec)","JBC 3","04-391-0445","OtherServices","","http://fourfrontiers.com"],
["mgrmc.png","MGR Management Consulting (Local Placement)","Fortune Tower","04-364-9347","Management Services","","http://mgrmc.com"],
["elitbuzz.png","Elitbuzz Technologies (IT services)","Fortune Tower","04-818-9666","IT Services","","http://elitbuzz.com"],
["ibgdubai.gif","IBG International Business Group (Buying & Selling Property)","Realestate Services","04-439-3644","OtherServices","","http://ibgdubai.com"],
["hl-display.png","HL Display Middle East (Trading )","Fortune Tower","04-424-0110","Trading Services","","http://hl-display.com/"],
["corp.png","Corp Trading Company","Fortune Tower","04-451-7227","Trading Services","","http://corp.com.tr"],
["comap.gif","ComAp Electronic Solutions","Fortune Tower","050-744-8680","Electronic Services","","http://comap.cz"],
["ikonpaper.png","Ikon Paper","Fortune Tower","04-448-6090","OtherServices","","http://ikonpaper.com"],
["","Acquaint Consulting (Investing in Human Capital)","Fortune Tower","04-450-8856","Investment Services","","http://acquaint-me.com"],
["companyptvgroup.png","PTV MENA Region","Fortune Tower","056-700-0095","OtherServices","","http://company.ptvgroup.com"],
["jca-associates.png","JCA Associates (Job consulting,Engineering)","Cluster C,Fortune Tower, Suit:2001","04-457-4058","Engineering Services","","http://jca-associates.com"],
["","MCOM Media Communications (TV & Mobile solutions)","Cluster C1, Fortune Tower, Suite:906","04-431-6630","Communication Services","","http://mcoms.com"],
["nasfid.jpg","Nasfid Consultancy (Accounting)","Cluster C1, Fortune Tower, Suite:206","04-448-4628","Accounting Services","","http://nasfid.ae"],
["gyproc.jpg","Saint-Gobain Gyproc Middle East (Project Solutions)","Cluster W, Tiffany Tower, Floor 40","04-450-2300","Project Solutions","","http://gyproc.ae"],
["rs-class.png","Russian Maritime Register of Shipping ME (shipping)","Cluster C1, Fortune Tower","04-369-7717","Logistic / Shipping Services","","http://rs-class.org"],
["boltongroup.png","Bolton Middle East","Fortune Tower","04-423-0618","OtherServices","","http://http.boltongroup.net"],
["flair-shipping.png","Flair Group (shipping)","Cluster C1, Fortune Tower, Suite:1604","04-442-3684","Logistic / Shipping Services","","http://flair-shipping.com"],
["spe.png","Society Petroleum Engineers","Fortune Tower","04-457-5800","Petroleum Engineering Services","","http://spe.org/"],
["kipcodamaco.png","Damaco Foods (Poultry Meat Products)","Cluster C1, Fortune Tower, Suite:202","04-421-10073","OtherServices","","http://kipcodamaco.com"],
["","Ahmed Consultants","Cluster C1, Fortune Tower","04-447-0388","Food Services","",""],
["acetechsvcs.png","AceTech Services DMCC (HR Resources)","Cluster C1, Suite:1006-1010","04-427-5085","HR Services","","http://acetechsvcs.com"],
["","Archea Association (consulting)","Cluster C1, Fortune Tower, Suite:3002","04-436-6323","Consultancy Services","","http://archea.it"],
["damanhealth.jpg","National Health Insurance Company-Daman","Cluster C1, Fortune Tower","800 432626","Insurance Services","","http://damanhealth.ae"],
["nickysfashion.png","Nickys Gift Shoppe JLT","Cluster B, Lake View, Suite:2","050-914-3416","OtherServices","","http://nickysfashion.com"],
["hridubai.jpg","Human Relations Institute & Clinics (HR relations)","JBC 3","04-365-8498","HR Services","","http://hridubai.com"],
["axisauditing.png","Axis Auditing & Accounting","Cluster C1, Fortune Tower","04-431-0156","Accounting Services","","http://axisauditing.com"],

["descoonline.png","Desco (copy & print center)","HDS Tower","04-433-7507/7508","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","HDS Business Centre","055-302-6162","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","Al Mas Tower","04-375-2059","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","Tiffany Tower","04-362-2055","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","Palladium","055-302-6214","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","JBC 1","04-434-5663/2","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["descoonline.png","Desco (copy & print center)","1 Lake Plaza","04-554-7678","Digital Services","http://www.descoonline.com/dubai-printing-press-locations/","http://descoonline.com/"],
["","V Print ","Cluster F","04-276-7571","Digital Services","","http://go.2gis.com/db8q2"],
["printstation.jpg","Print Station ","Cluster X","04-553-8632","Digital Services","","http://printstation.ae/"],
["theimprintstudio.jpg","IM Print Studio","Cluster T, Lake Plaza","04-423-2654","Digital Services","","http://theimprintstudio.com/about"],
["stardigitalprints.jpg","Star Digital Prints ","Cluster Y, Lake Shore Tower","04-551-6440","Digital Services","","http://stardigitalprints.com/online/"],
["jiffyprintz.jpg","Jiffy Printz","Cluster Y, JBC 5","04-422.4231","Digital Services","","https://shoutit.com/shout/1d17d1d9-b5e5-4fa5-ade9-305e2898b87f/Dubai/Jiffy-Printz"],
["trinityitsupplies.png","Trinity IT Supplies JLT","HDS Tower, Shop NO G16","04-422-9808","Digital Services","","http://trinityitsupplies.com/"],
["","Commscope","JBC 5","04-390-0980","OtherServices","","http://stardigitalprints.com/online/"],
["cadreprologo.png","Cad Repro Graphics LLC","Cluster B ","04-361-4445","Digital / Graphics Services","","http://cadreprographics.com/"],
["","Techno Graphics","Cluster T","04-361-8759","Digital / Graphics","","http://technographic.com.my/"],
["","New Phones Land JLT","Cluster B, Shop#15","04-434-1477","Digital Services","","https://facebook.com/phonelandJLT/"],
["smartplus.png","Smart Plus Services","Cluster J","04-431-2715","Typing Services","","https://facebook.com/Smart-Plus-Services-JLT-360025844174295/info?tab=overview"],
["","Taqat Tech","Cluster J","04-553-1460","OtherServices","","http://hridubai.com/"],
["","City Stationery JLT","Cluster J","04-423-2087","Stationery Shop","",""],
["techfield.png","Techfield DMCC","Jumeirah Lakes Towers, Dubai","04-427-2483 / 0502548667 ","Digital Services","https://goo.gl/maps/im8q9frDXdT2","http://emirate-dubai.yalwa.ae/ID_132351156/Techfield-JLT.html"],

["thechampionclubcom.png","The Champiob Club (Martial Arts)","Cluster L","04-447-4980","Fitness Center","","http://thechampionclub.com/index.php"],
["","Smart Fitness","Cluster M","04-438-5055","Fitness Center","","http://smartfitness.ae/"],
["targetgym.png","Target Gym","Cluster Q","04-421-0372","Fitness Center","","http://targetgym.ae"],
["fitnesszone.png","Fitness Zone ","Cluster R","04-451-0522","Fitness Center","","http://www.fitnesszonedubai.com/"],
["fitmyway.png","Fit My Way","Cluster X2, ShopNo:S 14","04-420-3677","Fitness Center","","http://fitmyway.net"],
["rails.png","Rails Billiards & Snooker ","Red Diamond, JLT","04-432-7742","Fitness Center","","http://rails.ae"],
["","Cool Look Aesthetic & Fitness Ceter","Cluster E, Lake View No:7-11","04-368-8736","Fitness Center","","http://jeaniqueyogaandpilates.com/"],
["jeaniqueyogaandpilates.png","Jeanique Yoga And Pilates JLT","Cluster I, Platinum Tower, Shop:510","055-788-5977","Fitness Center","",""],
["","Soul Fitness Club","Cluster A","04-438-0000","Fitness Center","","http://www.movenpick.com/en/middle-east/uae/dubai-jumeirah-lake-towers/wellness"],
["lifespark.png","Lifespark Reebok","Cluster H, Concorde Tower, Shop:G10","04-450-8234","Fitness Center","","http://reebokcrossfitlifespark.com/"],

["astermedicalcentrecom.png","Aster Medical Center","Red Diamond Building","04-420-4029","Clinics","https://google.ae/maps/dir/''/Red+Diamond+Building,+Near+Carrefour+Express+-+Jumeirah+Lake+Towers+-+Dubai/data=!4m5!4m4!1m0!1m2!1m1!1s0x3e5f6ca14d3c4213:0x23aef2f66cb81ede?sa=X&ved=0CCUQiBMwAGoVChMI3O7CguelxwIVRbwUCh0c0wDj","http://astermedicalcentre.com/"],
["astermedicalcentrecom.png","Aster Medical Center","Icon Tower, Ground Floor","055-700-9328","Clinics","","http://astermedicalcentre.com/"],
["amaldoctorcom.png","Dr. Amal Alias Clinic JLT (Obstetrician-Gynaecologist)","Cluster C, Fortune Tower","04-447-3976","Clinics","","http://amal-doctor.com/en/"],
["veincurecliniccom.png","VeinCure Clinic","Cluster E","04-375-6484","Clinics","https://google.ae/maps/dir/''/E11+-+Dubai/@25.0723298,55.1414618,11z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6cac136c1e33:0xda81a6a6335a5bfb!2m2!1d55.1414618!2d25.0723298","http://laclinique-me.com/"],
["lacliniquemecom.png","La Clinique ME","Cluster E, Saba 1, Unit 901","04-443-7895","Clinics","https://google.ae/maps/dir/''/Saba+1,+Suite+901,+Cluster+E+-+Jumeirah+Lakes+Tower+-+Dubai/@25.0719901,55.1071631,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6cac6bb1a06d:0x798350a457811cdc!2m2!1d55.141496!2d25.071994","http://laclinique-me.com/"],
["bodybalancerscom.png","Body Balancers JLT","HDS Tower","04-450-8487","Clinics","http://ae.nusalist.com/location/25.072451/55.142593/hds-tower-dubai-united-arab-emirates","http://bodybalancers.com/#sthash.d9Y6IWof.dpuf"],
["","Dr K Medical Center JLT","Cluster F, Indigo Icon Tower Unit:3205","04-447-7020","Clinics","","http://drbinitashah.com/"],
["totalhealthae.png","Total Health Chiropractic Clinic","Almas Tower, First Floor","055-133-2957","Clinics","","http://totalhealth.ae"],
["conceiveivfcom.png","Conceive Gynaecology & Fertility Hospital JLT","Red Diamond Building, Next to Careofour","04-554-5820","Clinics","","http://conceiveivf.com/"],
["","Royalcare Medical Center","1 Lake Plaza, 19th Floor","04-449-5335","Clinics","","http://conceiveivf.com/"],
["lacliniquemecom.png","La Clinique ME (Polyclinic)","Cluster E Saba 1","04-443-7895","Clinics","","http://laclinique-me.com/"],
["healthbaycliniccom.png","Health Bay Polyclinic","Cluster X2, Office No:409","04-456-5778","Clinics","","http://healthbayclinic.com"],
["","The Lakes Clinic JLT (dental) ","The Lakes Clinic JLT (dental) ","04-453-4848","Dental Clinics","https://google.ae/maps/dir/''/HDS+Tower+-+Dubai/@25.0722231,55.1083651,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6cac18c69841:0x299d3dae49f20df5!2m2!1d55.142698!2d25.072227",""],
["laperladentalcom.png","La Perla Dental Clinic JLT","Cluster V, JBC 2, Unit 904","04-432-1732","Dental Clinics","https://google.ae/maps/dir/''/Fortune+Tower+-+Dubai/data=!4m5!4m4!1m0!1m2!1m1!1s0x3e5f6cad161bfa07:0xb0539d0695a27234?sa=X&ved=0CA0QiBMoATADahUKEwjAst7M8aXHAhVDbxQKHSSzCHQ","http://laperladental.com/"],
["infinitydentalcliniccom.png","Infinity Dental Center","Fortune Tower Unit:1510","04-448-9270","Dental Clinics","https://google.ae/maps/dir/''/1510+Fortune+Tower+-+Jumeirah+Lake+Towers+-+Dubai/data=!4m5!4m4!1m0!1m2!1m1!1s0x3e5f6cad3e0b6e8d:0xbf699efc00e8d301?sa=X&ved=0CA8QiBMoATADahUKEwjSk7ic8qXHAhUB2RQKHR9lAFo","http://infinitydentalclinic.com/"],
["","German Dental Center","Cluster M, HDS Business Center, Unit 106","04-449-5335","Dental Clinics","https://google.ae/maps/dir/''/106,1st+floor,HDS+Business+Centre,Cluster+M,JLT+-+%D8%AF%D8%A8%D9%8A%E2%80%AD/data=!4m5!4m4!1m0!1m2!1m1!1s0x3e5f6cacebf92a71:0xbbbcb17a4aafaeb?sa=X&ved=0CA4QiBMoADADahUKEwjSl5yu8qXHAhULtBQKHR_ICDM",""],
["heydccom.png","HEY Dental Clinic DMCC","Goldcrest Executive Business Tower 105/106","04-450-8717","Dental Clinics","https://google.ae/maps/dir/''/Jumeirah+Lake+Towers+(JLT)+-+Goldcrest+Executive+Business+Tower+105%2F106+-+Dubai/@25.0687641,55.1052111,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x3e5f6cad12c3d935:0xc539ad96766c62cf!2m2!1d55.139544!2d25.068768","http://hey-dc.com/"],
["dubaiskycliniccom.png","Sky Clinic (Dental)","Cluster Y, Swiss Tower","04-355-8808","Dental Clinics","","http://dubaiskyclinic.com/"],
["lifemecom.png","Life Medical Center JLT","Cluster V, JBC, Unit 1204 & 1205","04-453-9633","Hospitals","https://google.ae/maps/dir/''/Red+Diamond+Building,+Near+Carrefour+Express+-+Jumeirah+Lake+Towers+-+Dubai/data=!4m5!4m4!1m0!1m2!1m1!1s0x3e5f6ca14d3c4213:0x23aef2f66cb81ede?sa=X&ved=0CBIQiBMwAGoVChMIzp3-9eelxwIVy14UCh3k5AOq","http://lifemedicalcenterjlt.com/"],
["armadahospitalcom.png","Armada Medical Center","Cluster P, Armada Tower 2 Unit: 19th floor","04-399-0022","Hospitals","","http://armadahospital.com/"],
["","Dr. 'K' Medical Center","Indigo Icon Tower No:3205","04-447-7020","Hospitals","","http://drkmedicalcentre.com/"],
["ydlmecom.png","YDL York Diagnostic Laboratories JLT","Cluster D, Indigo Tower, Office 509-510","800-YDL(935)","Hospitals","","http://ydl-me.com"],

["","UBK Watch Your Speed (Drinks deal)","cluster A","04-438-0000","Hotel Apartments","",""],
["moveandpick.png","Movenpick Hotel JLT","Cluster A, Building 2","04-438-0000","Hotel Apartments","","http://movenpick.com/en/middle-east/uae/dubai/dubai-jumeirah-lakes-towers/overview/"],
["bonnington.jpg","Bonnington Hotel Apartments","","","Hotel Apartments","","http://bonningtontower.com/"],
["","Pullman Hotel Apartments","","","Hotel Apartments","","http://pullman-jumeirah-lakes-towers.dubaihoteluae.com/en/"],
["OAKShotelsandresorts.gif","Oaks Hotels & Resorts","JBC","04-436-3434","Hotel Apartments","","http://oakshotelsresorts.com/"],

["zeninterior.png","Zen Interiors JLT","O2 tower","04-340-5050","Interior Designer","","http://zeninteriors.net/jumeirah-lake-towers-o2-tower-dubai-uae"],
["","Lake Side Interior","Cluster D2, Lake Terrace Tower","04-435-6067","Interior Designer","","http://go.2gis.com/2xh7"],
["","Office Fitouts","","04-457-9339","Interior Designer","",""],
["pallado.png","Palladio Interiors","Cluster, Indigo Icon Tower","04-427-9610","Interior Designer","","http://www.palladiointeriors.ae/"],
["levant.png","Levant (Mark of Luxury)","Cluster I, Silver Tower, Suite 19D&E","04-447-7940","Interior Designer","","http://levant.com/"],

["","Fluff N fold Laundry","Cluster B","04-369-7463","Laundry & Drycleaners","",""],
["","Royal Touch Automatic Laundry","Cluster E, Global Lake view","04-421-4215","Laundry & Drycleaners","",""],
["","Sparkle Line Laundry","Cluster F2, HDS Tower","04-368-8259","Laundry & Drycleaners","",""],
["","Al Mosky Laundry","Cluster P, Almada Tower1","04-344-0253","Laundry & Drycleaners","",""],
["","Lakes Laundry","Cluster Q","04-454-2505","Laundry & Drycleaners","",""],
["evershine-logo.png","Evershine Drycleaners","Cluster R","04-431-7191","Laundry & Drycleaners","","http://evershinelaundry.net"],
["","Suds R Us Laundry","Cluster T","04-363-5111","Laundry & Drycleaners","",""],
["","April Laundry","Cluster T","04-435-6239","Laundry & Drycleaners","",""],
["","AMS Dry cleaners & Laundry","Cluster U, Al Seef Tower","055-963-3786","Laundry & Drycleaners","",""],
["tjlaundry.jpg","Tom & Jerry Laundry","Cluster J2, Shop No.20","04-443-2575","Laundry & Drycleaners","","http://tjlaundry.com/contact.html"],
["","Veritas Dry Clean Laundry","Gold Crest View","04-447-1632","Laundry & Drycleaners","",""],

["kidskare.png","Kids Kare Nursery","Cluster E","04-441-7673","Nursery / Kids Care","","http://kidskarenursery.com/"],
["rainbowvalleynursery.png","Rainbow Valley Nursery","Cluster G","04-423-2540","Nursery / Kids Care","","http://rainbowvalleynursery.com/"],
["four2fourcare.png","Four 2 Four Nursery ","Cluster J1, Gold Crest Views","04-451-7450","Nursery / Kids Care","","http://four2fourcare.com/"],
["kidskingdom.png","Kids Kingdom","Cluster L","04-552-1585","Nursery / Kids Care","","http://kidskingdom.ae/"],
["","Baby Home Nursery","Cluster N","055-973-1097","Nursery / Kids Care","","http://babyhomenursery.com/"],
["tinytownnursery.jpg","Tiny Town - Play Lounge","cluster Q","04-883-0175","Nursery / Kids Care","","http://tinytownnursery.ae/"],
["learningladdernursery.png","Ladder Nursery","Cluster Q","056-728-3801","Nursery / Kids Care","","http://learningladdernursery.com/"],
["learningladdernursery.png","Ladder Nursery","Cluster V","04-277-5720","Nursery / Kids Care","","http://learningladdernursery.com/"],
["dewdropsnursery.jpg","Dew Drop Nursery","Cluster X,1, Jumeirah Bay X1","04-422-9397","Nursery / Kids Care","","http://dewdropsnursery.com/"],
["dewdropsnursery.jpg","Dew Drop Nursery","Cluster Y, JBC-2","04-368-6399","Nursery / Kids Care","","http://dewdropsnursery.com/"],
["mosaicnursery.png","Mosaic Nursery","Cluster F Fortune Tower","04-425-6670","Nursery / Kids Care","","http://mosaicnursery.com"],
["metamindz.png","Meta Mindz Learning Center","Red Diamond Center JLT","04-368-5604","Nursery / Kids Care","","http://metamindz.com/"],
["vernuselc.png","Vernus Nursery Learning Center","Cluster U","055-437-4282","Nursery / Kids Care","","http://vernuselc.ae/"],
["kiddiescafe.png","Kiddies Café","Cluster Y","04-360-8571","Nursery / Kids Care","","http://kiddiescafe.com"],

["petsinthecity.png","Pest in the City","Cluster D, Lake Terrace, Shop:3","04-458-0091","Pet(s) Care","","http://petsinthecity.me/"],
["","Petholicks - One stop Pet Shop","Cluster B, Lake View Tower","04-363-9635","Pet(s) Care","","http://petholicksdubai.com/"],
["europets.png","Europets","Cluster D. Lake Terrace Tower, Shop:7","04-421-4885","Pet(s) Care","","http://europets.net/"],
["petsplus.png","Pets Plus","Cluster Q, Gate Tower","04-440-5199","Pet(s) Care","","https://petsplus.ae/"],
["petshousedubai.png","Pet House","Cluster T, 1 Lake Plaza,Shop:11","04-552-0526","Pet(s) Care","","http://petshousedubai.com/"],
["petskygroup.jpg","Pet Sky","Cluster Y","04-456-2202","Pet(s) Care","","http://petskygroup.com/"],
["","Pompered Poochies SPA DMCC","Cluster C","04-276-7160","Pet(s) Care","","http://ppoochies.com/"],

["armadaholding.png","Armada Pharmacy","Cluster P, Armada Tower","04-397-7777","Pharmacy","","http://armadaholding.com/Healthcare/ArmadaPharmacy.aspx"],
["lifemecom.png","Life Pharmacy","Cluster E, Sabah Tower, Ground Floor","04-439-1776","Pharmacy","","http://life-me.com/"],
["lifemecom.png","Life Pharmacy - Real 7","Cluster X","04-551-6435","Pharmacy","","http://life-me.com/"],
["supercareae.png","Super Care Pharmacy JLT","Cluster E, Al shera Tower","04-454-1157","Pharmacy","","http://super-care.ae/"],
["asterpharmacy.png","Aster Pharmacy JLT","Red Diamond Bldg, Shop No: G011-B","04-369-7728","Pharmacy","","http://asterpharmacy.com/pharmacy/new-aster-pharmacy-jlt/"],
["wecarepharmaciescom.png","We Care Pharmacy","Cluster D, Lake City Tower, Shop:6","04-368 6411","Pharmacy","","http://wecarepharmacies.com/"],
["","Life Aid Pharmacy","Cluster V","04-431-7400","Pharmacy","",""],
["","Life New Al Kanz Pharmacy","Cluster J","04-392-9669","Pharmacy","",""],
["","Sarai Lakes Pharmacy","Cluster Q, Saba 2","04-447-1335","Pharmacy","",""],
["","New Mark Pharmacy","Cluster T, Fortune Executive","04-432-7303","Pharmacy","",""],
["","Health First Pharmacy","Cluster U. Al Seef 2","04-552-0732","Pharmacy","",""],
["","Alpha Pharmacy","Cluster W, JBC , Shop No.3","04-333-5520","Pharmacy","",""],
["","Sai Lakes Pharmacy","Cluster A","04-447-1337/1335","Pharmacy","",""],
["","Estilo Optics","shop#5, Al waleed Paradise, Cluste-R, ","+971-3608530","Pharmacy","","http://estilooptics.com/"],

["sherwoodsproperty.png","Sherwoods Property","Cluster O, Madina Tower","04-432-8221","Real Estate Services","","http://sherwoodsproperty.com"],
["core-me.jpg","Core Savills (Real Estate Property Services)","Almas Tower","04-423-9933","Real Estate Services","","http://core-me.com"],
["propspace.jpg","PropSpace Real Estate CRM ","Mazaya Business Avenue","04-420-1044","Real Estate Services","","http://propspace.com"],
["almasahint.png","Almasah International ","Reef Tower","04-422-4200","Real Estate Services","","http://almasahint.com"],
["sapphiredubai.jpg","Sapphire & Co. JLT","Goldcrest Executive","04-447-1778","Real Estate Services","","http://sapphiredubai.com"],
["orientdesertrealestate.png","Orient Desert Real Estate","Armada P3","04-435-6856","Real Estate Services","","http://orientdesertrealestate.com"],
["atomicproperties.jpg","Atomic Properties","1 Lake Plaza","04-434-2678","Real Estate Services","","http://atomicproperties.org"],
["betterhomes.png","BetterHomes","Cluster D","04-306-8722","Rent & Sales","","http://bhomes.com/"],
["","Zen Indigo Properties LLC","Indigo Tower","","Rent & Sales","","https://bayut.com/to-rent/apartments/dubai/discovery-gardens/zen/?gclid=CL24z4nuvMoCFYMIwwodgbUGDw#rd_purpose=2&cat_id=5237&property_type=4,17,12,14,16,3,10,8,13,9,5,11,15,6,7"],

["","Allons-y JLT","HDS Tower JLT","04-431-7242","Fast Food","",""],
["CharleysLogo.gif","Charley's Grilled Subs","Cluster E","04-438-5009","Fast Food","","http://charleysme.com/"],
["saltpepperme.jpg","Salt & pepper Village JLT","Cluster D, Lake Terrace Tower, Ground Level","04-421-4501","Fast Food","","http://saltpepperme.com/"],
["hardees.png","Hardees","Cluster I","055-219-6337","Fast Food","","http://hardees.com/"],
["kfcarabiajpg.jpg","KFC","Cluster I","055-219-6337","Fast Food","","http://kfc-arabia.com/english/home"],
["grabngouae.png","Grab N' Go","Cluster I","04-425-1930","Fast Food","","http://grabngouae.com/"],
["","Chesters","Cluster U","04-432-9029","Fast Food","",""],
["subwayarabia.jpg","Subway","Cluster Y","04-457-9212","Fast Food","","http://subwayarabia.com/countries.php"],

["Caffe_Nero_logo.png","Nero Café","Almas Tower Ground Level","04-439-0580","Café & Desseert","","http://caffenero.co.uk/uae/default.aspx"],
["","Sucre Sale (Italian)","Cluster E, Saba Tower 1","04-448-4648","Café & Desseert","","https://zomato.com/dubai/sucr%C3%A9-sal%C3%A9-jumeirah-lake-towers/menu"],
["","Moussa's Café JLT","Cluster C, Fortune Tower","04-447-1616","Café & Desseert","","http://moussas.net/"],
["","Red Rose-Mart & Coffee","Cluster D","04-427-9793","Café & Desseert","",""],
["","Take A Break (Café)","Cluster F","04-434-1339","Café & Desseert","","https://zomato.com/dubai/take-a-break-jumeirah-lake-towers"],
["","Café Le Flair","Cluster G, JBC 1","04-427-8629","Café & Desseert","",""],
["marcopoloespresso.png","Marco Polo expresso","Cluster G, JBC1","04-443-6790","Café & Desseert","","http://marcopoloespresso.com/"],
["HOMELiwaBanner1.jpg","Liwa Café","Cluster G, Arch Tower","04-450-8800","Café & Desseert","","http://liwa-cafe.com/"],
["rollingpinbakeryanddeli.png","Rolin Pin Bakery & Café","Cluster H, Concorde Tower","04-448-3335","Café & Desseert","","http://rollingpinbakeryanddeli.com/"],
["caffetrieste.png","Café Triesto","Cluster I, Platinum Tower","04-368-9455, 056-348-5526","Café & Desseert","","http://caffetrieste.ae/"],
["","Own café","Cluster I","04-441-3519","Café & Desseert","","http://own-cafe.quandoo.ae"],
["","Caffé Divino - Delice Ventures JLT","Cluster O, O2","04-363-8411","Café & Desseert","",""],
["","Mug Hug","Cluster P, Armada1","04-323-2610","Café & Desseert","",""],
["","Café Funkie Town","Cluster Q, Saba 3","04-368-9697/27","Café & Desseert","",""],
["menschcafe.png","Mensch Café","Cluster Q","04-420-7383","Café & Desseert","","http://menschcafe.com/"],
["","Laqmouche Kaak","Cluster R, MAG 214","04-456-6630","Café & Desseert","","https://zomato.com/dubai/restaurants/in/cluster-r-jumeirah-lake-towers"],
["publiccafe.png","Public Café","Cluster T, 1 Lake Plaza","04-451-9670","Café & Desseert","","http://publiccafeme.com"],
["","Friends Avenue Café","Cluster T, Fortune Executive","04-554-5813","Café & Desseert","",""],
["cafejulie.png","Café Julie","Cluster T, 1 Lake Plaza","04-364-9477","Café & Desseert","","http://cafejulie.com/"],
["fraiche.png","Fraiche Café & Bistro ","Cluster Y, Swiss Tower","04-369-7821","Café & Desseert","","http://fraiche.ae/"],
["","Estalian Coffee Break","Cluster Y, ","04-276-6184","Café & Desseert","",""],
["nofara.jpg","Nofara Café","Cluster Y, Swiss Tower","04-432-2023","Café & Desseert","","http://nofaracafe.com/"],
["","Baldwin Café","Cluster V, Gold Cluster View","04-447-7024","Café & Desseert","","jltbaldwin.com"],
["","G's café (Free WiFi)","Cluster F","04-391-8841","Café & Desseert","","http://gforme.ae/"],
["","Caffiology","Cluster G, jbc 1","056-934-9866","Café & Desseert","",""],
["fusion.png","Fusion Café","Cluster O, O2 tower","04-554-8159","Café & Desseert","","http://fusion.ae"],
["timhortons.png","Tim Hortons ","Almas Tower","055-597-6130","Café & Desseert","","http://timhortons.com/"],
["bonnington.jpg","Authors' Lounge","Cluster J,Bonnington Tower","04-356-0000","Café & Desseert","","http://bonningtontower.com/authors-lounge-dubai.asp"],
["rails.png","Rails Billiards & Snooker ","Red Diamond, JLT","04-432-7742","Café & Desseert","","http://rails.ae"],
["","Corner Café (Resto & Café)","Cluster X2 & Q","04-456-4984","Café & Desseert","","https://zomato.com/dubai/corner-cafe-jumeirah-lake-towers/menu"],


["DelhiDarbar.jpg","Delhi Dharbar","Cluster D, Indigo Tower","04-363-8660","Indian restaurants","","http://delhi-darbar.com/"],
["","Bombay Bites","Cluster C, GoldCrest Executive Tower","04-368-6365","Indian restaurants","",""],
["","Biriyani (Pakisthan & Indian)","Cluster T","800 DUMPUKHT","Indian restaurants","",""],
["","The Biriyani works","Cluster Q","04-553-0620","Indian restaurants","","https://zomato.com/dubai/dum-pukht-jumeirah-lake-towers"],
["","Jharokha (Indian & Chinese)","Cluster X2","04-361-9601","Indian restaurants","","http://jharokha.ae"],
["800thali.png","800 Thali Bowl Food JLT","Cluster B, Lakeview Tower","04-365-9959","Indian restaurants","","http://800thali.com"],
["","Flames Grills & curry JLT","Cluster D","04-425-6664","Indian restaurants","",""],
["","Anandha Bhavan","Cluster D","04-276-7392","Indian restaurants","",""],
["","5 Spice Restaurant","Cluster E","04-432-9346","Indian restaurants","",""],
["","Inlay Asia Restaurant","Cluster F","04-458-7117","Indian restaurants","",""],
["","Tandoori Junction","Cluster F","04-431-1866","Indian restaurants","","https://zomato.com/dubai/tandoori-junction-jumeirah-lake-towers/menu"],
["","Mughaliya","Cluster H","04-453-4861","Indian restaurants","",""],
["","101 Parathas","Cluster I","04-424-9950","Indian restaurants","",""],
["","Spice Kraft (veg)","Cluster I","04-363-5329","Indian restaurants","","https://zomato.com/dubai/spice-kraft-jumeirah-lake-towers"],
["","Bunny's tandoori","cluster J","04-441-4270","Indian restaurants","",""],
["","Memsaab (Tandoori)","Cluster J","04-442-9816","Indian restaurants","",""],
["","Appa Kadai","Cluster O","04-430-7029","Indian restaurants","",""],
["","Sagar Ratna","Cluster R","04-453-3364","Indian restaurants","","http://sagarratna.ae/"],
["","Chandini Chowk","Cluster T","04-427-9500","Indian restaurants","",""],
["","Punjabi Khu ","Cluster T","04-368-8791","Indian restaurants","",""],
["","Indian Delights","Cluster Y","04-360-3297","Indian restaurants","",""],
["","Doner Kebab","Cluster W","04-354-9174","Indian restaurants","",""],
["fusion.png","Fusion Restaurant (multicuisine)","Cluster G","04-369-5096","Indian restaurants","","http://fusion.ae/"],

["canadian2for1pizza.png","Canadian 2For1pizza","Gold Crest Executive Tower","04-448-3399","Pizza Place","","https://facebook.com/can2for1"],
["pizzamedubai.png","Pizzame (Little Italian in JLT)","Cluster J, J2 beside Bonnington Hotel","800-pizzame","Pizza Place","","http://pizzamedubai.com/"],
["","Jazz@Pizza express","Cluster  A","04-441-6342","Pizza Place","",""],
["","Pizza Delice","Cluster G","04-363-9990","Pizza Place","",""],
["","Pizza Hut","Cluster I","055-219-6337/600 56 9999","Pizza Place","",""],
["","Pizza Me","Cluster J","04-454-2723","Pizza Place","",""],
["","Pizzario","Cluster Q","04-453-9243","Pizza Place","",""],
["","Flour Pizza","Cluster X","04-453-9991","Pizza Place","",""],
["","Mambo Pizza","Cluster W","04-450-9876","Pizza Place","",""],

["","Fit Food Kitchen","Cluster J2","04-429-8844","Health simplified","",""],
["rightbite.png","The Right Bite","Cluster J, J2","04-550-9264","Health simplified","","http://right-bite.com/"],
["","Salt & Pepper Village Restaurant","Cluster D","04-421-4502","Health simplified","",""],
["","Just Salad","Cluster D","04-365-2222","Health simplified","",""],
["","Doctor Chef","Cluster H","04-277-5688","Health simplified","",""],
["","So Salad","Cluster Y","800 767 2523","Health simplified","","https://zomato.com/dubai/so-salad-jumeirah-lake-towers"],
["","Gram Italiana","","","Health simplified","",""],
["","Greenplanet (Green people Organic JLT)","Cluster U, Al Seef 2","04-369-5209","Health simplified","",""],
["richys.jpg","Richys Cafeteria","Cluster F, HDS Tower","800 742 497, 50-819-3202","Health simplified","",""],

["","Lean Cuts Butchery","","04-431-1068","Speciality Restaurants","",""],
["wokyo.png","wokyo Noodle Bar","Cluster J, J2 builg, Bonnington","800-wokyo (96596)","Speciality Restaurants","","http://wokyo.com/"],
["","Hanoi Café & Restaurant (Vietnamese)","Cluster C, GoldCrest Executive","04-431-3099","Speciality Restaurants","","https://zomato.com/hanoinaturallyJLTdubai/menu"],
["","Merlion's King Singaporean Cuisine","Platinum Tower, Shop NO G11","04-456-4954","Speciality Restaurants","",""],
["yinyang.png","Yin & Yang Restaurant (Chinese)","Cluster B","04-374-3899","Speciality Restaurants","","http://yinyangdubai.com/"],
["bluesapphirechinese.png","Blue Sapphre (Chinese)","Cluster I","04-451-5552","Speciality Restaurants","","http://bluesapphirechinese.com/"],
["hengchenme.png","Henchen (Chinese)","Cluster W","04-361-9893","Speciality Restaurants","","http://hengchenme.com/"],
["eastkitchen.png","EastKitchen (Chinese)","Cluster U3","04-422-6929","Speciality Restaurants","","http://eastkitchen.com"],
["","Chou Chou (Chinese)","Cluster F","04-276-6353","Speciality Restaurants","",""],
["","Chinese House","Cluster G","04-369-5096","Speciality Restaurants","",""],
["","Red Star Wok (Chinese)","Cluster G","04-458-6677","Speciality Restaurants","",""],
["","Chin Chin (Chinese)","Cluster N","04-276-0033","Speciality Restaurants","",""],
["","Homey (Chinese)","Cluster Y","04-431-7106","Speciality Restaurants","",""],
["","Hengchen (Chinese)","Cluster W","04-361-9893","Speciality Restaurants","",""],
["","East Asian Kitchen (Sushi & Chinese)","Cluster U","04-422-6929","Speciality Restaurants","","http://eastkitchen.com/eak2013/"],
["","Hako Sushi","Cluster I","055-801-0800","Speciality Restaurants","",""],
["","Albeet Betak Restaurant (Filipino Foods)","Cluster U2","04-425-2642","Speciality Restaurants","",""],
["","The Kitchen of Thai","Cluster C, GoldCrest Executive","04-451-2299","Speciality Restaurants","","https://zomato.com/dubai/the-kitchen-of-thai-restaurant-jumeirah-lake-towers/menu"],
["","Little Bangkok (Urban Thai Cuisine)","","800BANGKOK","Speciality Restaurants","","http://littlebangkok.com/"],
["mantoushe.png","Mantoushe","Cluster P","04-277-8170","Speciality Restaurants","","http://mantoushe.com/"],
["","Star Fish (Sea Food)","Cluster Q","04-434-0543","Speciality Restaurants","","https://zomato.com/dubai/star-fish-jumeirah-lake-towers/menu"],
["","4 Guys (Mexican)","Cluster T","04-435-7377","Speciality Restaurants","",""],
["alfayak.png","Ala Kayfak (Labanese)","Cluster U","04-453-9954","Speciality Restaurants","","http://alakayfak.com"],
["","Labanese Kitchen","Cluster Y","04-554-5872","Speciality Restaurants","",""],
["broccoli.png","Broccoli (Pizza & Pasta)","Cluster X","04-551-9319","Speciality Restaurants","","http://broccoli.ae"],
["","Corner Café (Resto & Café)","Cluster X2","04-456-4984","Speciality Restaurants","",""],
["centopercento.png","Centopercento (Italian)","Cluster X2","04-422-7975","Speciality Restaurants","","http://www.centopercento.ae/"],
["","Golositalia (Italian)","Cluster C, GoldCrest Executive","04-443-4955","Speciality Restaurants","",""],
["","Gramo Italian","Cluster F","04-210-7730","Speciality Restaurants","",""],
["","La Liga Sport Restaurant (Italian)","Cluster R","800 525 442","Speciality Restaurants","",""],
["NaisKitchenjpg.jpg","Nais Italian Kitchen","HDS tower","04-452-9991","Speciality Restaurants","","http://naiskitchen.com/"],
["","Il Lago","Cluster Y","04-452-0707","Speciality Restaurants","",""],
["","Nais Italian Kitchen","Cluster F","04-452-9991","Speciality Restaurants","",""],
["","Sizzle (Italian, Mexican)","Cluster U","800 749 953","Speciality Restaurants","","https://zomato.com/dubai/sizzle-jumeirah-lake-towers"],
["","Cento Per Cento - Pinocchio (Italian)","Cluster X","04-422-7975","Speciality Restaurants","",""],
["","The Kitchen of Thai","","","Speciality Restaurants","",""],
["lacartedubai.png","La Karte (French Homemade Cuisine)","Cluster Q","04-425-7963","Speciality Restaurants","","http://lacartedubai.com/"],
["lunchboxapoint.png","A Point (French & Meditteranean)","Cluster X1","04-399-8308","Speciality Restaurants","","http://lunchbox.apoint.ae"],
["icebergburgers.png","Iceberg (Burgers & sandwiches)","Cluster X2","800 iceberg","Speciality Restaurants","","http://icebergburges.com"],
["","Pressmans (fast food & sandwiches)","Cluster E","04-428-9459","Speciality Restaurants","",""],
["","Bon Burger","Cluster E","04-421-3639","Speciality Restaurants","",""],
["","Haji Ali (juice Center)","Cluster U2","04-554-6206","Speciality Restaurants","",""],
["kaeeek.jpg","Kaek Kaeeek (Labanese)","Cluster B, Lakeview Tower","04-553-0395","Speciality Restaurants","","https://www.facebook.com/kaekbakery"],
["","Wardat (Labanese)","Cluster C, GoldCrest Executive","04-452-1199","Speciality Restaurants","","https://zomato.com/dubai/wardat-lebanese-restaurant-jumeirah-lake-towers/menu"],
["","Kteer Tayyeb (Labanese)","Cluster C, GoldCrest Executive","04-456-0797","Speciality Restaurants","",""],
["lebanos.jpg","Lebanos (Lebanese & Mediterranean)","Cluster W","04-374-0117","Speciality Restaurants","","http://lebanos.net/"],
["","Iza Badak (Labenese, Arabian)","Cluster R","04-430-2960","Speciality Restaurants","","https://zomato.com/dubai/iza-badak-jumeirah-lake-towers"],
["","El Pasha (Arabian & Middle eastern)","Cluster W","04-421-4945","Speciality Restaurants","","https://zomato.com/dubai/el-pasha-restaurant-cafe-jumeirah-lake-towers"],
["","Favorite Lake (Indian,Chinese,Arabian)","Cluster R","","Speciality Restaurants","",""],
["","Jabal Lubnan Butchery","Cluster L","04-443-3738","Speciality Restaurants","",""],
["","Al-Romansiah","Cluster C, GoldCrest Executive","04-431-7070","Speciality Restaurants","",""],
["","Kol W Akelny (Labanese)","Cluster G","04-456-0520/35","Speciality Restaurants","",""],
["","Shawermaty Gourmet","Cluster C","04-451-6661","Speciality Restaurants","",""],
["","Shawerma Sojok JLT","Cluster J","04-276-7287","Speciality Restaurants","",""],
["","Labby's (Greek)","Cluster J","04-277-6926","Speciality Restaurants","",""],
["","Skazka Al Saha Restaurant (Russian)","Cluster M","04-452-2289","Speciality Restaurants","",""],
["","Mangal (Russian)","Cluster F, HDS Tower","04-277-1441","Speciality Restaurants","",""],
["","MOCKOBCKNE (Russian)","Saba 3, Shor No.3","","Speciality Restaurants","",""],
["","Chaykhona (Russian)","Cluster W","04-423-1011","Speciality Restaurants","",""],
["","Farsi Restaurant & Buffet","Clusster R","04-450-3532","Speciality Restaurants","",""],
["","NOSH seafood (Movenpick Hotel)","cluster A","04-438-0000","Speciality Restaurants","",""],
["","Grilled & Thrilled","Cluster Q","04-448-8522","Speciality Restaurants","",""],
["akawioven.gif","Akawi Oven","Cluster T","04-447-4404","Speciality Restaurants","","https://facebook.com/AkawiOven"],
["","Baguette Burger","Cluster Q","04-456-4984","Speciality Restaurants","",""],
["shiekandshake.png","Sheikh & Shake","Cluster R","04-452-2273","Speciality Restaurants","","http://sheikhandshake.com/"],
["","Q meal","Cluster R","04-451-0522","Speciality Restaurants","",""],


["","Sarang Bakery JLT","Cluster C","04-552-1284","Bakery","",""],
["","Donaccino (Desert & Bakery)","Cluster D","04-276-7110","Bakery","",""],
["","Rolin Pin Bakery & Café","Cluster H","04-448-3335","Bakery","",""],
["","Something Baked","Cluster J","04-362-9445","Bakery","","https://zomato.com/dubai/something-baked-jumeirah-lake-towers"],
["","Mister Baker","Cluster O","04-262-4150","Bakery","",""],
["","Baker Street","Cluster Q","04-362-9392","Bakery","",""],
["","Sukar House of Dessert & Bakery","Cluster Q","04-454-7805","Bakery","","https://zomato.com/dubai/sukar-house-of-desserts-jumeirah-lake-towers"],
["sukardesserts.jpg","Éclair Pastry JLT","Cluster Y","04-427-9901","Bakery","","https://facebook.com/sukardesserts"],
["","Looshi's Macarons Cake","Cluster Y","04-277-6190","Bakery","",""],
["gforme.png","G's café (Free WiFi)","Cluster F","04-391-8841","Bakery","","http://gforme.ae/"],

["","Succhara Organic Ice Cream","Cluster C","04-426-9062","IceCream & Dessert","","https://zomato.com/dubai/succharia-organic-ice-cream-jumeirah-lake-towers"],
["","London Dairy","Cluster W","050-918-7946","IceCream & Dessert","",""],

["mytailor.png","My Tailor & Little  Things","Cluster B. Lake View Tower","04-451-9090","Tailors","","http://mytailor.ae/"],
["","Tailor Made ","Cluster I,  Platinum Tower","04-453-3324","Tailors","","http://tailormade.ae/"],
["musicianssupplydubai.gif","Musicians Supply JLT","Cluster B, Lake View, Shop No:20","04-423-1132","Musicians","","http://musicianssupplydubai.com/"],
["comiccentraldubai.jpg","Comic Central JLT","Cluster D","050-457-1546","Comedy Central","","http://comiccentraldubai.com/"],
["royalfashion.gif","Royal Fashion ","Cluster C Goldcrest Executive ,Near Almas Tower ,Jumeirah Lake Towers","04-443-8766","OtherServices","","http://royalfashion.biz/"],
["uaeflowers.png","Dew Drop Florist ","Cluster H, Concorde Tower, Shop:G01","04-422-7036","Florist","","http://uaeflowers.com"],
["rosecharmsjlt.png","Rose Charms DMCC (Flower shop)","Cluster T, Lake Plaza, ShopNo: 18","04-458-8328","Florist","","http://rosecharmsjlt.com/"],

["carrefour.png","Carrefour Market Red Diamond","Cluster C","800 7 32 32","SuperMarkets","","http://carrefourexpressuae.com/"],
["carrefour.png","Carrefour Market","Cluster E","04-447-7699","SuperMarkets","","http://carrefourexpressuae.com/"],
["","Park'N Shop","Cluster P","04-447-1424","SuperMarkets","",""],
["carrefour.png","Carrefour","Cluster U","04-395-7435","SuperMarkets","","http://carrefourexpressuae.com/"],
["blueplanetgreenpeople.png","Blue Planet (organic)","Cluster X","04-389-5209","SuperMarkets","","http://blueplanetgreenpeople.com/"],
["","Spinneys'","Cluster X","04-395-1641","SuperMarkets","",""],
["","Joudi Supermarket","Cluster U, Al Seef 2","04-454-9525","SuperMarkets","","http://jumeirahguide.com/917/supermarkets/joudi-mini-mart-in-jumeirah-lake-towers"],
["blueplanetgreenpeople.png","Greenplanet (Green people Organic JLT)","Cluster Q","04-369-5209","SuperMarkets","","http://blueplanetgreenpeople.com/"],
["geantuae.png","Geant Easy Supermarket","","04-435-7353","SuperMarkets","","http://geant-uae.com/jlt-dubai"],
["","Twins mini Mart","Cluster B","04-447-4213","Mini Marts","",""],
["","Green Bean Store JLT","Cluster B","04-277-6972","Mini Marts","",""],
["","Mohed Grocery","Cluster B","04-457-2944","Mini Marts","",""],
["","Shabab Minimart","Cluster C","04-448-4371","Mini Marts","",""],
["","Nigt Mart","Cluster D","04-447-5383","Mini Marts","",""],
["","Charley's Dolphin Foods JLT","Cluster E","04-438-5009","Mini Marts","",""],
["","Q Mart","Cluster R","04-450-3849","Mini Marts","",""],
["","Q Mart","Cluster R","04-447-2151","Mini Marts","",""],
["","Zoom Market","Cluster A","04-431-3257","Mini Marts","","http://www.zoomcstore.com/"],
["","Zoom Market","Cluster S","04-425-8125","Mini Marts","","http://www.zoomcstore.com/"],
["","Zoom Market","Cluster Y","04-360-7839","Mini Marts","","http://www.zoomcstore.com/"],
["","Zoom Market","Cluster F","04-431-3257","Mini Marts","","http://www.zoomcstore.com/"],
["","Zoom Market","Cluster M","04-425-8125","Mini Marts","","http://www.zoomcstore.com/"],
["","Zoom Market","Cluster T","04-425-8125","Mini Marts","","http://www.zoomcstore.com/"],
["","Manila Mart","Fortune Executive Tower, T1, Cluster T","04-276-5705","Mini Marts","","http://2gis.ae/dubai/firm/70000001018040231?queryState=center%2F55.149275%2C25.078907%2Fzoom%2F17"],
["","Zataar","Cluster U","04-432-8689","Mini Marts","",""],
["","West Zone Fresh Supermarket","Cluster U","04-453-1964","Mini Marts","",""],
["","Rouse Mini Mart","Cluster W","04-447-4688","Mini Marts","",""],
["","Rubi Mart","Cluster W","04-432-1188","Mini Marts","",""],
["lakesmart.png","Lakes Mart JLT","Saba 2","04-374-6788","SuperMarkets","","http://lakesmart.ae"],


["","The First Studio (Dance School)","Cluster A, Lake Side Residence","04-453-9691","Training / Learning Centers","","http://thefirststudio.wix.com"],
["tempodubai.png","Tempo Dance Center ","Red Diamond Center JLT","04-420-2393","Training / Learning Centers","","http://tempodubai.com/"],
["crystaldancecenter.png","Crystal Dance Center (Ballroon Dancing)","Cluster N, Dome Tower, 15th Floor","052-285-8304","Training / Learning Centers","","http://crystaldancecenter.com/"],
["arthurmurray.png","Arthur Murray Ballroom Dance","Reef Tower, No 201","04-448-6458","Training / Learning Centers","","http://arthurmurray.com"],
["musicalexpress.png","Musical Express Institute","Cluster N, JBC 4","04-553-0757","Training / Learning Centers","","http://musical-expression.com/"],
["tctiudc.jpg","The Coffee Training Institute (Coffee Brewing Tech)","Dubai Arch center","04-451-6363","Training / Learning Centers","","http://tctiudc.com/"],
["scafa.png","Scafa (Culinary School)","Cluster I, Promenage Level,No:6","04-379-4044","Training / Learning Centers","","http://scafa.ae/"],
["goldenfalconkarate.gif","Golden Falcon Karate","Fortune Executive Tower","04-450-8538","Training / Learning Centers","","http://goldenfalconkarate.com"],
["berlitz.png","Berlitz language center","Indigo Icon 11th Floor","04-457-2263","Training / Learning Centers","","http://rainbowvalleynursery.com"],
["","Golden Age Institute (Learn Arabic)","Swiss Tower","04-453-3046","Training / Learning Centers","","http://berlitz.ae/"],
["marjanbeauty.jpg","Marjan Training Centre (hair,nail, skincare)","Saba 1, 7th Floor","04-423-3700","Training / Learning Centers","","http://marjanbeauty.ae/"],
["","Benton ","JBC5, 29th Floor:2902","050-871-6205","Training / Learning Centers","","http://makeuptrainingcenter.com/"],
["speak.png","Speak - English Language institute","Cluster S","04-431-1232","Training / Learning Centers","","http://speak.ae/"],

["eaglerider.png","Eagle Riders (MotorCycleRental)","Cluster H - Concorde Tower","04-430-6400","OtherServices","","http://eaglerider.ae/"],
["","Bikers ","Cluster H","052-622-1888","OtherServices","",""],
["dubailinktours.png","Dubai Link (travel & Tours)","Movenpick Hotel JLT","04-448 8111","OtherServices","","http://dubailinktours.com/"],
["","Exotic Tours & Travels","Cluster W","04-441-5671","OtherServices","","http://exotictoursandtravels.com"],
["southtravels.png","South Travel JLT","Cluster F, HDS Tower","04-447-3839","OtherServices","","http://southtravels.com/"],
["acme-travels.png","Acme Travel & Tours JLT","Cluster P, Armada Tower 2","04-379-4787","OtherServices","","http://acme-travels.com/"],
["aaarentacarjlt.jpg","AAA Rent A Car","Cluster D3, Lake Tower City","04-360-3337","OtherServices","","http://aaarentacarjlt.com/"],
["pcr.png","PCR-Premium Car Rentals","Cluster G, Jumeirah Business Center G","04-360-9991","OtherServices","","http://pcr.ae/"],
["","777 Rent A Car","Cluster Q","04-363-8582","OtherServices","",""],
["indigojlt.png","Indigo Rent A Car","Cluster T","04-43506504/056-744-8008","OtherServices","","http://indigojlt.com"],

["stepbystep.png","Step By Step","Clust T, One Lake Plaza","04-420-1743","Digital Services","","http://stepbystepjlt.com"],
["fixit.png","Fixit Express","Almas -Tower, Shop No:01-26","04-427-6606","Digital Services","","http://fixituae.com"],
["cardiolates.png","Cardiolates","Cluster X2, ShopNo:4202","056-798-4655","Fitness Center","","http://cardiolatesmiddleeast.com"],
["yogaashram.png","Yoga Ashram","Cluster X3, Suite 1504","04-360-9028/056-281-5554","Fitness Center","","http://yogaashram.com"],
["palldiointeriors.png","Palldiointeriors","Jumeirah Lakes Towers Jewellery & Gemplex 3","+971 55-754-1324","Interior Designer","","http://www.palladiointeriors.ae/"],
["","We Love Pizza (Italian)","Cluster U, Al Seef Tower 2, UnitG04","04-457-7907/7908","Pizza Place","","https://www.facebook.com/pages/We-Love-Pizza-JLT/384835368392584?__mref=message_bubble"],
["etfetter.png","E & T Feteer","Cluster J,J2 Tower Unit 16","04-456-0806","Speciality Restaurants","","http://facebook.com/eatfeteer"],
["ds2dio.png","Ds2dio","Cluster T, One Lake Plaza","055-849-6193","Training / Learning Centers","https://goo.gl/maps/n9VPmV9cgkT2","https://www.theentertainerme.com/outlets/ds2dio/detail?m=6865&o=11989"],

["zenasiaspa.png","Zen Asia Spa in JLT","JBC 5 Basement","04-457-2374/75/76","Spa","","http://zenasiaspa.com"],
["","Natural Spa JLT","Cluster D","04-374-1686","Spa","","http://naturalspajlt.com/"],
["lotusmrc.png","Lotus Spa & retreat JLT","Cluster J","800 56887","Spa","","http://lotusmrc.com/"],
["","Body & Mind Relaxation Center","Cluster O","04-447-8855","Spa","","https://groupon.ae/deals/body-and-mind-relaxation-center"],
["","Oasis Spa Center JLT","Cluster R, MAG214","04-277-5874","Spa","","http://mazkara.com/dubai/oasis-spa-center-jumeirah-lakes-towers-jlt"],
["","Top Art Nail Spa","Cluster R","056-254-3755","Spas","","https://facebook.com/topartnail.spa"],
["bodysky.png","Body Sky JLT","Cluster U2","04-441-8034","Spa","","http://bodyskyjlt.com"],
["","Naturo Pathy CTpuch","Cluster X","04-360-4443","Spa","","http://nptouch.com/"],
["primadonna.png","Prima Donna","","04-554-7853","Spa","","http://primadonna.ae"],
["icequeen.png","Ice Queen (Wellness Spa Center)","Cluster Q1, Saba 3","04-430-7954","Spa","","http://icequeen.ae/"],
["","Naturopathy Touch","Cluster D & Cluster X2","04-452.6969","Spa","","https://facebook.com/NaturopathyTouch/"],
["","The White Room (Beauty & Spa)","Cluster U; Shop No 2","04-422-8997","Spa","","http://whiteroomdubai.com"],
["marjanbeauty.png","Marjan (hair,nail, skincare)","Saba 1, ShopNo:6","04-423-3700","Beauty Salon","","http://marjanbeauty.ae/"],
["agbeautycenter.png","Avant Garden Beauty Centre","Cluster C","04-450-8608","Beauty Salon","","http://agbeautycentre.com/spa-salon-dubai/"],
["","Diana Beauty Castle ","Cluster C","04-368-6635","Beauty Salon","","http://dianabeautycastle.com/"],
["","Beauty Story Salon","Cluster A","04-362-1412","Beauty Salon","","https://facebook.com/beautystorysalonJLT/"],
["","Amore Hair & Beauty Salon","Cluster B","04-435-6474","Beauty Salon","",""],
["","Holiday Nails JLT","Cluste B","04-458-7861","Beauty Salon","","https://facebook.com/Holiday-Nails-JLT-353616137990923/"],
["","Avant Beauty Garde Center","Cluster C","04-437-0288","Beauty Salon","","http://agbeautycentre.com/spa-salon-dubai/"],
["","Ava Beauty Salon","HDS Tower, UnitNo:207","04-422-8076","Beauty Salon","","https://facebook.com/AVA-Beauty-Saloon-JLT-317462698297575/"],
["tiptop.png","Tip Top Beauty Lounge","Cluster C","04-454-1146","Beauty Salon","","http://tiptopbeautylounge.com/"],
["","Bright Beauty Salon","Cluster C, Gold Crest Tower","04-551-6915","Beauty Salon","","http://mazkara.com/dubai/bright-beauty-salon-jumeirah-lakes-towers-jlt"],
["","Budur beauty Salon","Cluster D","04-277-6347","Beauty Salon","","http://mazkara.com/dubai/budur-beauty-salon-jumeirah-lakes-towers-jlt"],
["","Wax Works Ladies Salon","Cluster D","04-447-3541","Beauty Salon","","https://facebook.com/Wax.Works.Salon"],
["","I Glow Beauty Lounge","Cluster D","04-420-9667","Beauty Salon","","http://iglowbeauty.ae/"],
["","Amro Style Salon","Cluster G","04-426-9966","Beauty Salon","","https://www.facebook.com/AmroStyle/"],
["","Le Michael salon ","Bonnigton Hotel","04-356-0544","Beauty Salon","",""],
["essabeauty.png","Essa Beauty","Cluster G","04-374-4288","Beauty Salon","","http://essabeauty.com"],
["","Jameela Beauty Salon","Cluster H","04-425-9683","Beauty Salon","","http://jameelasalon.com/"],
["","Mera Salon","Cluster I","04-448-3071","Beauty Salon","","https://facebook.com/Mera-Salon-JLT-352760678200545/"],
["","Le Salon","Cluster I","04-452-1117","Beauty Salon","","http://lesalondubai.com/"],
["lemichelsalon.png","Le Michel Salon","Bonnigton Hotel","04-356-0544","Beauty Salon","","http://lemichelsalon.com"],
["","Aleph Salon","Cluster J","04-369-5420","Beauty Salon","","http://mazkara.com/dubai/aleph-gents-salon-jumeirah-lakes-towers-jlt"],
["","La Femme Beauty Salon","Cluster J","04-430-3125","Beauty Salon","","https://facebook.com/lafemmejlt/"],
["","Malikah Beauty Salon","Cluster J","04-454-2902","Beauty Salon","","http://www.mazkara.com/dubai/malikah-beauty-salon-jumeirah-lakes-towers-jlt"],
["","Look Salon S'n'S Esthetics","Cluster N","04-276-7544","Beauty Salon","",""],
["","Cavallo Nera Gents Salon","Cluster P","04-458-6835","Beauty Salon","",""],
["","La Beautique Beauty Salon","Cluster Q","04-450-8468","Beauty Salon","","http://labeautique-salon.com/"],
["","Zana Salon","Cluster Q","04-422-8471","Beauty Salon","","http://mazkara.com/dubai/zana-gents-salon-jumeirah-lakes-towers-jlt"],
["","Rousha Salon","Cluster Q","04-421-7931","Beauty Salon","","https://facebook.com/Rousha-Salon-521076157934065/"],
["","Sharp Gents Salon ","Cluster R","04-369-7457","Beauty Salon","","https://facebook.com/SHARPGentsSalon"],
["sunfacebeauty.png","Sun Face beauty Salon","Cluster R, MAG214,Shop:6","04-453-9784","Beauty Salon","","http://sunfacebeauty.com"],
["wgents.png","W Gents Salon","Cluster T, Lake Plaza Shop:GF17","04-450-8810","Beauty Salon","","http://wgentssalon.com"],
["","Mary Beauty Salon","Cluster T","04-447-1860","Beauty Salon","","http://www.marybeautysalon.com/"],
["addressbeautycom.png","Adres Beauty Salon","Cluster U, Al Seef 2","04-431-3043","Beauty Salon","","http://address-beauty.com"],
["scentsationsalon.png","Scentsations Ladies Salon JLT","Cluster X","04-364-9276","Beauty Salon","","http://scentsationSalon.com"],
["","Real Beauty","cluster Y","04-421-4267","Beauty Salon","","http://nailthedeal.com/7907/multiple-beauty-services"],
["","Nail Pavillion","Cluster Y","04-422-9791","Beauty Salon","","https://facebook.com/The-Nail-Pavilion-501105043333375/"],
["","Natalie Beauty Salon","Cluster V","04-435-8077","Beauty Salon","","http://www.nataliebeautysaloon.com/"],
["","O & O Beauty Centre","Cluster T","04-276-5998","Beauty Salon","","https://facebook.com/OO-Beauty-Center-793339750730587/"],
["mazkara.png","Crystal Beauty Lounge JLT (Spa,Salon)","Red Diamond JLT","04-368-8664","Beauty Salon","","http://mazkara.com/dubai/crystal-beauty-lounge-jumeirah-lakes-towers-jlt"],
["personabeautysalon.png","Persona (Ladies & Gents Salon)","Cluster O, Madina Tower","04-422-8205","Beauty Salon","","https://facebook.com/Persona-Ladies-Gents-Beauty-Salon-JLT-154476004629244/"],
["juansalon.png","Juan Salon ","Indigo Tower, 3rd Floor","04-438-9570","Beauty Salon","","http://juansalon.com"],
["","Mankind (spa JLT)","Almas Tower","04-429-8668","Beauty Salon","","http://mydubaimycity.com/video/mankind"],
["sensessalonjlt.png","Senses Salon JLT","Cluster W,Tiffany Tower","04-457-2290","Beauty Salon","","https://vaniday.ae/salons/sensessalonjltladies?gclid=CMLrgJ3YvMoCFarpwgodRZsK8Q"],
["beautycenterdubai.png","Alessia Spa & Salon","Cluster F, HDS Tower,15thFloor","04-447-1599","Beauty Salon","","http://beautycenterdubai.com/"],
["","Close cut Barbder Shop","Cluster D","050-457-1546","Hair Salon","","http://mazkara.com/dubai/close-cut-barber-shop-jumeirah-lakes-towers-jlt"],
["","In The Hair JLT","Cluster F","056-143-6709","Hair Salon","","http://tipntag.com/place/s/in-the-hair-1-JLT"],
["","GQ Lounge Men Hair Lounge","Cluster T","04-434-0518","Hair Salon","","http://gqlounge.wix.com/male-salon"],
["lucastoppony.png","Luca Stoppony","Cluster T, Lake Plaza","055-889-2136","Hair Salon","","http://lucastoppony.com"],
["smarthairways.png","Smart Hairways Gents Salon","Cluster U<.Al Seef 3, Chop:506","04-425-3536","Hair Salon","","http://smarthairways.com"],
["","Tang & Mora (Hair design & Spa)","","","Hair Salon","","http://mazkara.com/dubai/tang-mora-gents-spa-jumeirah-lakes-towers-jlt"],
["","Jamalich Beauty Salon","Arch Tower","04-447-7303","Hair Salon","","http://jamalich.ae/"],
["","Amro Style Salon","UB shop No:6","050-472-5400","Hair Salon","","https://www.facebook.com/AmroStyle/"],
["","Mike Beauty Salon","Armada Tower 1, HC-34th","04-395-8888","Hair Salon","","https://facebook.com/Mike-Salon-Armada-beauty-JLT-229302417205411/"],
["epicbeauty.png","EPIC BEAUTY DMCC","Green Lakes Towers S3, Shop S20, Ground Level","+971 044471815 / +971 507744988","Beauty Salon & Spa","https://goo.gl/maps/Y5w8uv31icr","http://epicbeautydubai.com"],
["armadaspa.png","Armada Spa","Armada Tower 1, HealthClub Floor","04-395-8888","Hair Salon","","http://armadaspa.com"]


];
    
  

 
$(document).ready(function() {
    $('#searchresultsData').DataTable( {
        data: dataSet,
        columns: [
            { title: "", bSortable: false },
            { title: "Name", "sClass": "datatables_action"},
            { title: "Address" },
            { title: "Contact No." },
            { title: "Type" },
            { title: "Map", bSortable: false},
            { title: "Website" ,"width" : "10%"}
        ],
        
          "order": [[ 1, "asc" ]],
          "oSearch": {"sSearch": JLTTools.getParameterByName("searchParam")},
        
        "aoColumnDefs": [
                          {
                              "aTargets":[0],  
                              "mRender": function ( data, type, row ) {
                            	//  console.log("mrender Called -",data);
                            	  if(data==""){
                            		  return "<img width=150 height=150 src='images/mockThumbnail.png' class='mockThumbnail'>";
	                        	  }else{
	                        		  return "<img width=150 height=150 src='images/jltfacility/jltsearchresults/"+data+"'>";
	                              }
                              }
                          },
                          {
	                          "aTargets":[5],  
	                          "mRender": function ( data, type, row ) {
	                        	//  console.log("mrender Called -",data); 
	                        if(data==""){
                        		  return "<span>N.A</span>";
                        	  }else{
	                              return "<a href="+data+" target='_blank'>Map</a>";
                        	  }
	                          }
                          },
                          {
	                          "aTargets":[6],  
	                          "mRender": function ( data, type, row ) {
	                        	 // console.log("mrender Called -",data);
	                        	  if(data==""){
	                        		  return "<span>N.A</span>";
	                        	  }else{
	                        		  return "<a href="+data+" target='_blank'>"+data+"</a>";
	                        	  }
	                          }
                          }
             ]

    } );
} );